### ISSUE TITLE
format of "version history"

### ISSUE THREAD

**Issue by tortinator** [potassco/guide#1]
I rewrite the text on complying system versions in 'frontpage.tex'
but I am unsure whether this is what we want
An alternative idea..?

**Comment by tortinator** [comment]
Also, we may want to mention that all current code is compatible with the current versions

**Comment by rkaminsk** [comment]
Not sure we really need a version log. Just the actual version and what it covers might be enough. Maybe referring to the previous iteration. But I would not go any further. This will just get lengthy over time. Something like: This is the Potassco guide version 3.0 documenting clingo 5.2, etc.

Btw. we might want to make a big version bump because clingo also had one.

**Comment by rkaminsk** [comment]
> Also, we may want to mention that all current code is compatible with the current versions.
The ASP code is. The API is not.

**Comment by tortinator** [comment]
I have to think about it and discuss this with you tomorrow (offline)
